export const testIds = {
  home: {
    hero: "home-hero",
    ctaDiscord: "home-cta-discord",
  },
  serverSelect: {
    root: "server-select",
    card: "server-card",
    open: "server-open",
  },
  nav: {
    library: "nav-library",
    ask: "nav-ask",
    billing: "nav-billing",
    settings: "nav-settings",
    adminConfig: "nav-admin-config",
  },
  library: {
    page: "library-page",
    search: "library-search",
    refresh: "library-refresh",
    archiveFilter: "library-archive-filter",
    meetingRow: "library-meeting-row",
    drawer: "meeting-drawer",
    drawerContent: "meeting-drawer-content",
    summaryScroll: "meeting-summary-scroll",
    summaryViewport: "meeting-summary-scroll-viewport",
    download: "meeting-download",
    archive: "meeting-archive",
    unarchive: "meeting-unarchive",
    archiveConfirm: "meeting-archive-confirm",
    loading: "library-loading",
  },
  ask: {
    page: "ask-page",
    new: "ask-new",
    title: "ask-title",
    input: "ask-input",
    send: "ask-send",
    message: "ask-message",
    listMode: "ask-list-mode",
    renameInput: "ask-rename-input",
    rename: "ask-rename",
    archive: "ask-archive",
    unarchive: "ask-unarchive",
    archiveConfirm: "ask-archive-confirm",
    conversationItem: "ask-conversation-item",
    loadingList: "ask-loading-list",
    loadingPane: "ask-loading-pane",
  },
  billing: {
    page: "billing-page",
    currentPlan: "billing-current-plan",
    plans: "billing-plans",
    planFree: "billing-plan-free",
    manage: "billing-manage",
    interval: "billing-interval",
  },
  settings: {
    page: "settings-page",
    addChannel: "settings-add-channel",
    modal: "settings-channel-modal",
    refreshChannels: "settings-refresh-channels",
    override: "settings-override",
    removeOverride: "settings-remove-override",
    saveChannel: "settings-save-channel",
    saveConfig: "settings-save-config",
    loadingConfig: "settings-loading-config",
    loadingOverrides: "settings-loading-overrides",
  },
  adminConfig: {
    page: "admin-config-page",
    publish: "admin-config-publish",
    refresh: "admin-config-refresh",
  },
} as const;
